export enum UserConstants {
    REQUEST_USER_DATA = 'REQUEST_USER_DATA',
    REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS',
    REQUEST_USER_ERROR = 'REQUEST_USER_ERROR',
    USER_ROLE = 'USER_ROLE'
}