export enum BasketConstants {
    SET_USER_ID = 'SET_USER_ID',
    ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET',
    REMOVE_ITEM_FROM_BASKET = 'REMOVE_ITEM_FROM_BASKET',
    CLEAR_BASKET = 'CLEAR_BASKET',
    CHANGE_QUANTITY_ITEM = 'CHANGE_QUANTITY_ITEM',
}