export enum ProductConstants {
    REQUEST_PRODUCTS_DATA = 'REQUEST_PRODUCTS_DATA',
    REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS',
    REQUEST_PRODUCTS_ERROR = 'REQUEST_PRODUCTS_ERROR',
    SET_EDIT_ID = 'SET_EDIT_ID',
    REMOVE_EDIT_ID = 'REMOVE_EDIT_ID'
}